name: quranapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  flutter_islamic_icons: ^1.0.2
  hijri: ^3.0.0
  arabic_numbers: ^1.0.0
  flutter_qiblah: ^3.0.4
  permission_handler: ^11.3.1
  flutter_neumorphic: ^3.2.0
  smooth_page_indicator: ^1.2.0+3
  shared_preferences: ^2.3.2
  adhan: ^2.0.0+1
  intl: ^0.19.0
  semicircle_indicator: ^1.1.1
  provider: ^6.1.2
  http: ^1.2.2
  location: ^7.0.1
  flutter_bloc: ^8.1.6
  geolocator: ^13.0.1
  flutter_svg: ^2.0.10+1
  adhan_dart: ^1.1.2
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  animated_toggle_switch: ^0.8.3
  another_xlider: ^3.0.2
  dropdown_button2: ^2.3.9
  share_plus: ^10.1.1
  image: ^4.3.0
  clipboard: ^0.1.3
  bot_toast: ^4.1.3
  shared_map: ^1.1.9
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.1.3
  carousel_slider: ^5.0.0
  audioplayers: ^6.1.0
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  scrollable_positioned_list: ^0.2.3
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^18.0.1
  googleapis_auth: ^1.6.0
  app_settings: ^5.1.1
  dio: ^5.7.0
  timezone: ^0.10.0
  animated_splash_screen: ^1.3.0
  just_audio: ^0.9.43 
  flutter_cache_manager: 
  internet_connection_checker: ^3.0.1
  fluttertoast: ^8.2.10
  awesome_dialog: ^3.2.1
  quran: ^1.2.9
  page_transition: ^2.1.0
  we_slide: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/image/Rafeqe.png"
    min_sdk_android: 21 # android min sdk min:16, default 21
    remove_alpha_ios: true
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/books/
    - assets/lottie/
    - assets/images/
    - assets/sounds/
    - assets/quranImages/
  






  fonts:
    - family: uthmanic
      fonts:
        - asset: assets/fonts/UthmanTN1_Ver10.otf
    - family: uthmanic2
      fonts:
        - asset: assets/fonts/UthmanicHafs_V20.ttf
    - family: kufi
      fonts:
        - asset: assets/fonts/Kufam-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/Kufam-VariableFont_wght.ttf
          weight: 500
        - asset: assets/fonts/Kufam-Regular.ttf
          weight: 100
    - family: naskh
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-VariableFont_wght.ttf
    - family: vexa
      fonts:
        - asset: assets/fonts/VEXA.ttf
          weight: 800
        - asset: assets/fonts/VEXA-light.ttf
          weight: 500
        - asset: assets/fonts/VEXA-ITALIC.ttf
          style: italic
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: QuranFont
      fonts:
         - asset: assets/fonts/Al Majeed Quranic Font_shiped.ttf
  #       - asset: fonts/Schyler-Italic.ttf   
    # - family: quran
    #   fonts:
    #     - asset: assets/HafsSmart_08.ttf
    # - family: me_quran
    #   fonts:
    #     - asset: assets/me_quran.ttf

# Configure flutter_launcher_icons
# flutter_icons:
 
