// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWh3pG8Dw4exyCHOoxKX1ipLbw6sgTHwo',
    appId: '1:867260458621:web:acac9b7d59739c5935b314',
    messagingSenderId: '867260458621',
    projectId: 'rafeqe-app',
    authDomain: 'rafeqe-app.firebaseapp.com',
    storageBucket: 'rafeqe-app.firebasestorage.app',
    measurementId: 'G-CQ6MJ3HN3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3hQIAyRoK0lHtuTHz6yJCQZlPYEeHqGU',
    appId: '1:867260458621:android:2409b7505afe265335b314',
    messagingSenderId: '867260458621',
    projectId: 'rafeqe-app',
    storageBucket: 'rafeqe-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPSOq6pzPBNYAiVOCAoKN0AyToewIS35s',
    appId: '1:867260458621:ios:523febc13975b99035b314',
    messagingSenderId: '867260458621',
    projectId: 'rafeqe-app',
    storageBucket: 'rafeqe-app.firebasestorage.app',
    iosBundleId: 'com.example.rafeqapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPSOq6pzPBNYAiVOCAoKN0AyToewIS35s',
    appId: '1:867260458621:ios:523febc13975b99035b314',
    messagingSenderId: '867260458621',
    projectId: 'rafeqe-app',
    storageBucket: 'rafeqe-app.firebasestorage.app',
    iosBundleId: 'com.example.rafeqapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWh3pG8Dw4exyCHOoxKX1ipLbw6sgTHwo',
    appId: '1:867260458621:web:776da15cef62974c35b314',
    messagingSenderId: '867260458621',
    projectId: 'rafeqe-app',
    authDomain: 'rafeqe-app.firebaseapp.com',
    storageBucket: 'rafeqe-app.firebasestorage.app',
    measurementId: 'G-5FQPF0WX55',
  );
}
